In [3]:
# Importing the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:

# Importing the dataset
df=pd.read_csv("cracow_apartments.csv")
print(df.head())
print(df.shape)
print(df.isnull().sum())

   distance_to_city_center  rooms   size    price
0                      2.4    1.0  19.35  191.565
1                      2.4    2.0  13.08  221.568
2                      5.0    1.0  24.66  185.936
3                      1.9    1.0  24.82  275.502
4                      1.9    1.0  25.39  241.205
(76, 4)
distance_to_city_center    0
rooms                      0
size                       0
price                      0
dtype: int64


In [8]:
# Defining x and y
x = df.iloc[:,0:3].values
y = df.iloc[:,3].values
print(x)
print(y)


[[  2.4    1.    19.35]
 [  2.4    2.    13.08]
 [  5.     1.    24.66]
 [  1.9    1.    24.82]
 [  1.9    1.    25.39]
 [  5.9    1.    25.54]
 [  3.     1.    25.62]
 [  9.     1.    26.04]
 [  8.4    1.    26.26]
 [  8.4    1.    26.26]
 [  2.5    1.    26.6 ]
 [  6.7    1.    26.87]
 [  8.5    1.    27.85]
 [  2.4    2.    27.86]
 [  3.4    1.    27.93]
 [  2.3    1.    28.32]
 [  1.4    3.    29.  ]
 [  2.     1.    29.91]
 [  1.9    2.    30.83]
 [  6.3    2.    31.68]
 [  5.9    2.    32.02]
 [  7.4    2.    32.22]
 [  2.7    2.    34.32]
 [  7.4    2.    34.32]
 [  4.     2.    34.78]
 [  7.6    2.    35.01]
 [  7.1    2.    37.11]
 [  4.9    2.    37.41]
 [  5.5    2.    38.7 ]
 [  1.5    3.    29.  ]
 [  8.7    3.    45.15]
 [  2.5    3.    48.17]
 [  9.     3.    48.52]
 [  6.4    3.    49.42]
 [  5.7    3.    49.44]
 [  3.8    3.    50.91]
 [  7.6    3.    51.9 ]
 [  4.1    3.    52.4 ]
 [  3.4    3.    52.7 ]
 [  4.7    3.    53.61]
 [  7.4    3.    53.83]
 [  7.4    3.   

In [9]:
# Splitting the dataset into Training set and Test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)


In [10]:
# Importing the model
from sklearn.linear_model import LinearRegression
lr = LinearRegression()


In [11]:
# Fitting the model
lr.fit(x_train, y_train)

LinearRegression()

In [13]:
#Predict
y_pred = lr.predict(x_test)
print("Predicted values \n",y_pred)
print("Training data score :", lr.score(x_train,y_train))
print("Testing data Score:", lr.score(x_test,y_test))

Predicted values 
 [489.09796544 585.82468507 312.67064831 234.88870351 287.21089241
 241.01251332 309.51288237 528.11994608 348.11315337 133.06074389
 347.95648386 583.73174908 346.27099761 346.03900847 333.12595131
 317.40151822]
Training data score : 0.9480633896446401
Testing data Score: 0.9369931160084563


In [15]:
# Model evaluation
from sklearn import metrics
rmse = np.sqrt(metrics.mean_squared_error(y_test, y_pred))
R2 = metrics.r2_score(y_test, y_pred)
print("RMSE Score :",rmse)
print("R2_score :",R2)



RMSE Score : 33.4341201190193
R2_score : 0.9369931160084563


In [21]:
'''
# Predicting by giving the own values
print("Predicted price :")
print(lr.predict([[1.7,3,42.5]]))  #distance_from_city_center = 1.7, 3BHK,size=42.5
'''

'\n# Predicting by giving the own values\nprint("Predicted price :")\nprint(lr.predict([[1.7,3,42.5]]))  #distance_from_city_center = 1.7, 3BHK,size=42.5\n'

In [18]:
# Saving model using pickle
import pickle
#import joblib
with open ('model_pickleoct','wb') as f:
    pickle.dump(lr,f)

In [22]:
# Saving model using joblib
import joblib
joblib.dump(lr,'model_jobliboct')

['model_jobliboct']

In [23]:
# For pickle model
with open('model_pickleoct','rb') as f:
    mop=pickle.load(f)
distance = float(input("Enter distance from city center :"))
room = int(input("Enter no of room:"))
size = float(input("Enter size of the room :"))
print("Predicted price :",mop.predict([[distance,room,size]]))
#print("predicted price :",mop.predict([[2.7,3,25.9]]))

Enter distance from city center :4.2
Enter no of room:2
Enter size of the room :25.3
Predicted price : [211.13522653]


In [25]:
# For joblib model
mo = joblib.load('model_jobliboct')
distance = float(input("Enter distance from city center :"))
room = int(input("Enter no of room:"))
size = float(input("Enter size of the room :"))
print(mo.predict([[distance,room,size]]))

Enter distance from city center :5
Enter no of room:3
Enter size of the room :56.3
[415.99387967]
